### ISSUE TITLE
Bug: Can't see links

### ISSUE THREAD

**Issue by niklasvatn** [datasektionen/pico#20]
Not sure when this happens, but I can't display my links. I can go to the links page, it says that I have five links but none is shown.
<img width="1272" alt="image" src="https://user-images.githubusercontent.com/55627591/191033841-2f742b51-086a-45e6-b35b-3ef5d0b83b66.png">

**Comment by elmaxe** [comment]
Use Chrome, works there

**Comment by Herkarl** [comment]
From my testing, this seem to be related to firefox.

Tested on plenty of operating systems and for several users.
In all cases, links did not show firefox, but did in chrome

I assume it should work on everything chromium-based, but haven't tested anything that is not chrome
