### ISSUE TITLE
Bug: Internal server error when authorizing user who's not in the dfunkt database

### ISSUE THREAD

**Issue by mathiasmagnusson** [datasektionen/pico#50]
These lines:
https://github.com/datasektionen/pico/blob/master/middlewares.ts#L55-L59
Retrvieves the user's current mandates from dfunkt. If the user does not exist in dfunkt's database (i.e. if the user has neither had a mandate in the chapter nor logged in on the website) dfunkt returns a 404. This is not handled and we just return a 500 without any logs.

dfunkt should probably return an empty array of mandates for unknown users, but pico should arguably not rely on dfunkt to work to allow users to create links.

**Comment by Herkarl** [comment]
I think the pico relying on dfunkt is in order for the "mandate-owned" links feature to work, but yeah, it should obviously be able to handle an error-response
