### ISSUE TITLE
Copy button need to copy with https:// before

### ISSUE THREAD

**Issue by Adasjo** [datasektionen/pico#9]
If copy button is pressed then it will give dsekt.se/xyz it should give https://dsekt.se/xyz

**Comment by elmaxe** [comment]
Is fixed by using `constructShortUrlWithProtocol` instead of `constructShortUrl` at 
https://github.com/datasektionen/pico/blob/882077db617a8ebb9b3e65e615a55fbc8bfc2765/client/src/common/functions.js#L2
